[helpers]

[settings]
default_target_type = "automatic"

[cargo.files]
cargo = "~/.cargo"

[git.files]
"git/gitconfig" = "~/.gitconfig"
"git/gitignore_global" = "~/.gitignore_global"

[npm.files]
".npmrc" = "~/.npmrc"

[starship.files]
starship = "~/.config"

[uv.files]
uv = "~/.config"

[vim.files]
"vim/vimrc" = "~/.vimrc"
