[bat.files]
bat = "~/AppData/Roaming/bat"

[git_bash.files]
"git/bashrc" = "~/.bashrc"

[helix.files]
helix = "~/AppData/Roaming/helix"

[pip.files]
"pip" = "~/AppData/Roaming/pip"

[pwsh.files]
"pwsh/profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[sublime.files]
sublime = "~/AppData/Roaming/Sublime Text/Packages/User"

[terminal.files]
"terminal/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

[zed.files]
zed = "~/AppData/Roaming/Zed"
